### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by Alexey71** [TBoneWiz/kernel_samsung_mondrianwifi#3]
But settings crashed. Try install clean, go to settings - system tuner - recent apps panel = crash
After turning off the screen, "hardware button back" does not go into sleep mode. If you press on it, the screen is switched on

[recent apps panel.txt](https://github.com/TBoneWiz/kernel_samsung_mondrianwifi/files/710729/recent.apps.panel.txt)

[Key button back.txt](https://github.com/TBoneWiz/kernel_samsung_mondrianwifi/files/710741/Key.button.back.txt)

**Comment by Alexey71** [comment]
`01-01 00:12:55.251  4795  4828 I ActivityManager: Displayed com.android.settings/.Settings: +363ms
01-01 00:13:20.368  4795  4811 I ActivityManager: START u0 {cmp=com.slim.settings/.activities.InterfaceSettingsActivity} from uid 1000 on display 0
01-01 00:13:20.385  4608  4970 D audio_hw_primary: select_devices: done
01-01 00:13:20.417  4795  5521 I ActivityManager: Start proc 6828:com.slim.settings/1000 for activity com.slim.settings/.activities.InterfaceSettingsActivity
01-01 00:13:20.524  6828  6828 W System  : ClassLoader referenced unknown path: /system/app/SlimSettings/lib/arm
01-01 00:13:20.532  5435  5889 D OpenGLRenderer: endAllStagingAnimators on 0xb3564e80 (RippleDrawable) with handle 0x9dabeba0
01-01 00:13:20.615  6828  6857 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-01 00:13:20.748  6828  6857 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Ia10634f51b)
01-01 00:13:20.748  6828  6857 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
01-01 00:13:20.748  6828  6857 I Adreno-EGL: Build Date: 01/28/16 Thu
01-01 00:13:20.748  6828  6857 I Adreno-EGL: Local Branch: ss
01-01 00:13:20.748  6828  6857 I Adreno-EGL: Remote Branch:
01-01 00:13:20.748  6828  6857 I Adreno-EGL: Local Patches:
01-01 00:13:20.748  6828  6857 I Adreno-EGL: Reconstruct Branch:
01-01 00:13:20.751  6828  6857 I OpenGLRenderer: Initialized EGL, version 1.4
01-01 00:13:20.903  4795  4828 I ActivityManager: Displayed com.slim.settings/.activities.InterfaceSettingsActivity: +496ms
01-01 00:13:22.831  4795  5490 I ActivityManager: START u0 {act=android.intent.action.MAIN cmp=com.slim.settings/.SubSettings (has extras)} from uid 1000 on display 0
01-01 00:13:22.883  6828  6828 D AndroidRuntime: Shutting down VM
01-01 00:13:22.884  6828  6828 E AndroidRuntime: FATAL EXCEPTION: main
01-01 00:13:22.884  6828  6828 E AndroidRuntime: Process: com.slim.settings, PID: 6828
01-01 00:13:22.884  6828  6828 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.slim.settings/com.slim.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.ListPreference.setEnabled(boolean)' on a null object reference
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5437)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-01 00:13:22.884  6828  6828 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.ListPreference.setEnabled(boolean)' on a null object reference
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at com.android.settings.slim.RecentPanel.initializeAllPreferences(RecentPanel.java:289)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at com.android.settings.slim.RecentPanel.onCreate(RecentPanel.java:101)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.Fragment.performCreate(Fragment.java:2198)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.BackStackRecord.run(BackStackRecord.java:794)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:562)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at com.slim.settings.SubSettings.switchToFragment(SubSettings.java:123)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at com.slim.settings.SubSettings.onCreate(SubSettings.java:95)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6251)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
01-01 00:13:22.884  6828  6828 E AndroidRuntime:        ... 9 more
01-01 00:13:22.886  4795  4811 W ActivityManager:   Force finishing activity com.slim.settings/.SubSettings
01-01 00:13:22.890  4795  4811 W ActivityManager:   Force finishing activity com.slim.settings/.activities.InterfaceSettingsActivity
01-01 00:13:22.927  4795  5946 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Ia10634f51b)
01-01 00:13:22.927  4795  5946 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
01-01 00:13:22.927  4795  5946 I Adreno-EGL: Build Date: 01/28/16 Thu
01-01 00:13:22.927  4795  5946 I Adreno-EGL: Local Branch: ss
01-01 00:13:22.927  4795  5946 I Adreno-EGL: Remote Branch:
01-01 00:13:22.927  4795  5946 I Adreno-EGL: Local Patches:
01-01 00:13:22.927  4795  5946 I Adreno-EGL: Reconstruct Branch:
01-01 00:13:22.927  4795  5946 I OpenGLRenderer: Initialized EGL, version 1.4
01-01 00:13:23.390  4795  4819 W ActivityManager: Activity pause timeout for ActivityRecord{d53ae1e u0 com.slim.settings/.SubSettings t10 f}
01-01 00:13:23.531  5435  5435 D DashboardSummary: rebuildUI took: 80 ms
01-01 00:13:25.961  4608  4970 D audio_hw_primary: out_standby: enter: stream (0xb60b6ac0) usecase(1: low-latency-playback)
01-01 00:13:26.039  4608  4970 D hardware_info: hw_info_append_hw_type : device_name = speaker-cdp
01-01 00:13:27.957  4608  4970 D audio_hw_primary: start_output_stream: enter: stream(0xb60b6ac0)usecase(1: low-latency-playback) devices(0x2)
01-01 00:13:27.957  4608  4970 D audio_hw_primary: start_output_stream: enter: usecase(1: low-latency-playback) devices(0x2)
01-01 00:13:27.957  4608  4970 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: )
01-01 00:13:27.957  4608  4970 W msm8974_platform: Codec backend bitwidth 16, samplerate 48000
01-01 00:13:27.957  4608  4970 D hardware_info: hw_info_append_hw_type : device_name = speaker-cdp
01-01 00:13:27.957  4608  4970 I msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 15, path =  0
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> send_adm_topology
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> send_audtable
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
01-01 00:13:27.957  4608  4970 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> send_audvoltable
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
01-01 00:13:27.957  4608  4970 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> send_afe_cal
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
01-01 00:13:27.957  4608  4970 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
01-01 00:13:27.957  4608  4970 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
01-01 00:13:27.965  4608  4970 D audio_hw_primary: select_devices: done
01-01 00:13:27.980  6828  6828 I Process : Sending signal. PID: 6828 SIG: 9
01-01 00:13:27.987  4795  5946 D OpenGLRenderer: endAllStagingAnimators on 0x9f2e6c00 (RippleDrawable) with handle 0x9c55b2e0
01-01 00:13:28.023  4795  5521 D GraphicsStats: Buffer count: 5
01-01 00:13:28.023  4795  5521 I WindowState: WIN DEATH: Window{6adcd5d u0 com.slim.settings/com.slim.settings.activities.InterfaceSettingsActivity}
01-01 00:13:28.120  4795  5441 I ActivityManager: Process com.slim.settings (pid 6828) has died
01-01 00:13:28.120  4795  5441 D ActivityManager: cleanUpApplicationRecord -- 6828
01-01 00:13:28.129  4795  4828 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0`
